### ISSUE TITLE
Blender 4.2: Known Issues from Update

### ISSUE THREAD

**Issue by ItsEasyActually** [X-Hax/SonicAdventureBlenderIO#23]
Opening this Issue to serve as a central spot to keep track of error reports coming in regarding changes from users regarding problems with the addon in 4.2 Should help consolidate work when it comes to updating the addon to work on 4.2.

### Verified Issues
- Models cannot be exported
  - Blender Error: `AttributeError: 'TrangulateModifier' object has no attribute 'keep_custom_normals'`

**Comment by kawaiikaorichan** [comment]
I found that the issue with "keep_custom_normals" is related to an ommision made by Blender devs. Seems they forgot to add that option to the Triangulate modifier.
[](https://projects.blender.org/blender/blender/issues/124690)

**Comment by Justin113D** [comment]
Fixed in release 2.2.0
